### ISSUE TITLE
getChild problem on Centos 6.6/Python 2.6.6

### ISSUE THREAD

**Issue by kmand** [dsoprea/GDriveFS#104]
I have GDriveFS working on Ubuntu 14.04, but ran into trouble on Centos 6.6. It seems the issue is that Centos is running Python 2.6.6 which doesn't support getChild. Is there a workaround?

Here is the backtrace
# gdfstool auth -u

Traceback (most recent call last):
  File "/usr/bin/gdfstool", line 16, in <module>
    from gdrivefs.gdfs.gdfuse import set_auth_cache_filepath, mount, \
  File "/usr/lib/python2.6/site-packages/gdrivefs/gdfs/gdfuse.py", line 23, in <module>
    from gdrivefs.change import get_change_manager
  File "/usr/lib/python2.6/site-packages/gdrivefs/change.py", line 9, in <module>
    from gdrivefs.cache.volume import PathRelations, EntryCache
  File "/usr/lib/python2.6/site-packages/gdrivefs/cache/volume.py", line 735, in <module>
    class EntryCache(CacheClientBase):
  File "/usr/lib/python2.6/site-packages/gdrivefs/cache/volume.py", line 739, in EntryCache
    about = AccountInfo.get_instance()
  File "/usr/lib/python2.6/site-packages/gdrivefs/general/livereader_base.py", line 57, in get_instance
    LiveReaderBase.**instances[class_name] = cls()
  File "/usr/lib/python2.6/site-packages/gdrivefs/gdtool/account_info.py", line 19, in __init**
    self.__log = logging.getLogger().getChild('AccountInfo')
AttributeError: RootLogger instance has no attribute 'getChild'
